### ISSUE TITLE
"The protocol will have mappings on top of WebTransport and directly on top of QUIC."

### ISSUE THREAD

**Issue by SpencerDawkins** [moq-wg/moq-charter#4]
I think these two mappings should be in the charter. 

My question is whether there should also be a mapping on top of H3. If you're trying to reuse HTTP caching and CDN infrastructure, do you have to use WebTransport to do that?

I'm thinking especially about people in the MPEG DASH-IF world. They're using DASH-IF, running over HTTP/1.1, and not using WebTransport at all. I'd love to push MOQ in (for instance) 3GPP SA4, but that's an easier lift if they're adjusting to HTTP/3 than switching to WebTransport.

**Comment by fluffy** [comment]
Makes sense to me but I don't understand all the implications of this. Would this end up replicating some of what WebTransport does to sit on top of H/3 ?

**Comment by LPardue** [comment]
I can see how we might want to define MoQ notions of reliable stream data and unreliable messages, and then map those to lower layers that might support them natively (or not!). QUIC and WebTransport (over HTTP/3, which effectively allows punching through to access QUIC features) can support native mapping. Molding standard HTTP semantics to support these things might be more tricky but feasible. But is might be a thin end of the wedge on changing HTTP too much from what can work on commodity cloud.

**Comment by SpencerDawkins** [comment]
> Makes sense to me but I don't understand all the implications of this. Would this end up replicating some of what WebTransport does to sit on top of H/3 ?

@fluffy, maybe my question should have been phrased as 

_"Do we think people would rather use WebTransport even if they don't run in a browser?"_

**Comment by GrumpyOldTroll** [comment]
> My question is whether there should also be a mapping on top of H3. If you're trying to reuse HTTP caching and CDN infrastructure, do you have to use WebTransport to do that?
> 
> I'm thinking especially about people in the MPEG DASH-IF world. They're using DASH-IF, running over HTTP/1.1, and not using WebTransport at all. I'd love to push MOQ in (for instance) 3GPP SA4, but that's an easier lift if they're adjusting to HTTP/3 than switching to WebTransport.

I think @SpencerDawkins raised a good point; if we want caching to be part of the delivery chain (e.g. to support saner rewind/etc) we probably need an H3 mapping specified, I would think.

**Comment by fluffy** [comment]
The more I think about it, the less I care what the container that carries the bits. I feel strongly I want a QUIC mapping, WebTransport makes sense for cases where this is over H3, and I can don't have any strong objections H3.

I note that the people that want to run in browsers expect to be on WebTransport. The people that don't want to be in a browser want the simplicity gains of not doing a full blow H3 implementation.  WebTransport and raw Quic are pretty much the same thing (minus the stream IDs) so I see these two aligning well as about the same work. Once we switch into H3 mappings, it seems there will be large pressure to make things align with things like low latency version of HLS  or DASH which might result in something much different.

**Comment by wilaw** [comment]
`"Do we think people would rather use WebTransport even if they don't run in a browser?"`
Likely yes, because scalability is going to come via CDN support and as a CDN we would prefer to support as few protocols as possible with the broadest reach. Candidates here would be H3 and WebTransport. WebTransport gives browser clients stream and datagram access and will give non-browser clients (which could use QUIC directly) a well supported and scalable distribution infrastructure. So I'd like to see solutions developed within MoQ to map cleanly to WebTransport. This is also an opportune time for this group to provide input to [Issue 21:](https://github.com/w3c/webtransport/issues/21) Access to congestion control and bandwidth estimation and [Issue 365](https://github.com/w3c/webtransport/issues/365): Pluggable Congestion Control, such that WebTransport will in turn map cleany to solutions developed under MoQ.
